projects = [
    {
        "projectName": "LeetCode Clone",
        "projectDescription": "A platform to practice logic-based programming questions. Supports multiple languages (Python, Java, C, C++).",
        "projectTechnologies": [
            "Express.js",
            "React.js",
            "PostgreSQL",
            "Redis",
            "Docker",
            "Prisma ORM",
            "Shadcn/UI",
            "Azure",
        ],
        "link": "https://code.manangandhi.tech/",
        "repo": "https://github.com/MananGandhi1810/online-ide",
    },
    {
        "projectName": "MPSTME OnTrack",
        "projectDescription": "MPSTME OnTrack helps students store their schedule and class details. Currently has 1500+ downloads on Play Store and App Store combined.",
        "projectTechnologies": ["Flutter", "Google Play Store", "Apple App Store"],
        "link": "https://ontrack.mpstme.tech/",
        "repo": "",
    },
    {
        "projectName": "Save Birds Admin Dashboard",
        "projectDescription": "Admin dashboard for the Save Birds NGO, allowing for easy management and monitoring of bird rescue and rehabilitation efforts.",
        "projectTechnologies": [
            "React.js",
            "Express.js",
            "MySQL",
            "Docker",
            "Oracle Cloud Infrastructure",
            "Shadcn/UI",
            "Redis",
            "Prisma ORM",
        ],
        "link": "",
        "repo": "",
    },
    {
        "projectName": "Chess",
        "projectDescription": "A scalable chess game playable by multiple users at the same time.",
        "projectTechnologies": [
            "Flutter",
            "Express.js",
            "Socket.io",
            "PostgreSQL",
            "Redis",
            "Docker",
            "Prisma ORM",
            "Azure",
        ],
        "link": "https://chess.manangandhi.tech/",
        "repo": "https://github.com/MananGandhi1810/online-chess",
    },
    {
        "projectName": "FluxGate",
        "projectDescription": "Self-hostable deployment platform to deploy GitHub repos to self-hosted servers; includes natural-language deploy option. Winner — Best use of Gemini API at HackThisFall Virtual 2024.",
        "projectTechnologies": [
            "Express.js",
            "Next.js",
            "Docker",
            "PostgreSQL",
            "Prisma ORM",
            "Redis",
            "Gemini 1.5 Flash",
            "Shadcn/UI",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/FluxGate",
    },
    {
        "projectName": "Adeon",
        "projectDescription": "An open source developer microtools platform designed to streamline and enhance the software development lifecycle using AI. Features include AI-powered Code Documentation Generation, Pull Request Analysis, Vulnerability Scanning, Development Environment Provisioning and CI/CD triggered Deployments.",
        "projectTechnologies": [
            "Express.js",
            "Next.js",
            "Docker",
            "PostgreSQL",
            "Prisma ORM",
            "Redis",
            "Gemini 1.5 Flash",
            "Shadcn/UI",
        ],
        "link": "https://adeon.me/",
        "repo": "https://github.com/MananGandhi1810/Adeon",
    },
    {
        "projectName": "Automated Interview Platform",
        "projectDescription": "Interview simulation platform that provides feedback and scoring to help users improve. Built for Smart India Hackathon 2024.",
        "projectTechnologies": [
            "Express.js",
            "Next.js",
            "MongoDB",
            "Gemini 1.5 Flash",
            "Python",
            "Apache Kafka",
            "Redis",
            "Docker",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/Vichaar-Manthan-SIH-2024",
    },
    {
        "projectName": "SKVJUM: A Community App",
        "projectDescription": "A community app for the members of Shree Khambhat Vishashrimali Jain Upnagar Mandal.",
        "projectTechnologies": ["Flutter", "Flask", "MongoDB", "AWS", "Google Play Store"],
        "link": "https://play.google.com/store/apps/details?id=com.skvjum.skvjum_app",
        "repo": "",
    },
    {
        "projectName": "BrainyBox",
        "projectDescription": "An edutainment platform that helps students learn concepts in an interactive way. 1st runner up at IET Hack n Code, MPSTME.",
        "projectTechnologies": [
            "Express.js",
            "Flutter",
            "Docker",
            "Firebase",
            "Google Maps API",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/BinaryBandits-HnC-2024",
    },
    {
        "projectName": "DreamScale",
        "projectDescription": "AI-powered personal startup advisor guiding solo founders through each stage of their journey. Developed at Cyber Cypher 4.0 Round 1.",
        "projectTechnologies": [
            "Flask",
            "React.js",
            "Gemini 2.0 Flash",
            "Docker",
            "Shadcn/UI",
            "TLDraw",
            "SerpAPI",
            "MongoDB",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/cc-4.0-round-1",
    },
    {
        "projectName": "HomeConnect",
        "projectDescription": "HomeConnect — a project built to demo full-stack features and collaboration (details in linked repo).",
        "projectTechnologies": [
            "Flask",
            "React.js",
            "Gemini 2.0 Flash",
            "Docker",
            "Shadcn/UI",
            "TLDraw",
            "SerpAPI",
            "MongoDB",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/cc-4.0-round-1",
    },
    {
        "projectName": "YetiCode",
        "projectDescription": "Web application to reduce development time and bugs. Winner at Datathon 3.0 by Analytika MPSTME.",
        "projectTechnologies": [
            "Next.js",
            "TailwindCSS",
            "Express.js",
            "Flask",
            "GitHub API",
            "Gemini 2.0 Flash",
            "PostgreSQL",
            "Prisma ORM",
            "Resend API",
            "Docker",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/datathon-round-2",
    },
    {
        "projectName": "DockerSensei",
        "projectDescription": "Docker container management system for managing and monitoring containers across servers.",
        "projectTechnologies": ["Node.js", "Docker", "Next.js", "Express.js", "PostgreSQL"],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/dockersensei",
    },
    {
        "projectName": "LLM Breakout",
        "projectDescription": "The classic Breakout game with a twist of Generative AI. Runner up for Most Fun Project in Supabase Launch Week 15 Hackathon.",
        "projectTechnologies": ["React.js", "FastAPI", "Supabase", "Gemini 2.5 Flash"],
        "link": "https://lw15.akshaykripalani.tech/",
        "repo": "https://github.com/akshaykripalani/supahack-lw15",
    },
    {
        "projectName": "AdGen",
        "projectDescription": "Platform for competitive intelligence, market analysis and social sentiment tracking across channels. Built at Level Supermind Hackathon.",
        "projectTechnologies": [
            "Next.js",
            "FastAPI",
            "LangChain",
            "AstraDB",
            "FireCrawl",
            "SerpAPI",
            "YouTube Comments API",
            "YT-dlp",
            "Auth0",
            "Gemini 2.0 Flash",
            "Reddit API",
            "Docker",
        ],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/level-supermind-hackathon-2025",
    },
    {
        "projectName": "cloudflare_ai (Dart)",
        "projectDescription": "A Dart library for using Cloudflare Workers AI to perform various AI-based operations.",
        "projectTechnologies": ["Dart", "Cloudflare"],
        "link": "https://pub.dev/packages/cloudflare_ai",
        "repo": "https://pub.dev/packages/cloudflare_ai",
    },
    {
        "projectName": "Conversify",
        "projectDescription": "An app to help people discover others across domains to build projects together. Built during a 24-hour hackathon.",
        "projectTechnologies": ["Flutter", "Firebase"],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/Verbal-Virtuosos-Debate-a-thon",
    },
    {
        "projectName": "Stock Market Game",
        "projectDescription": "A realtime online multiplayer game simulating a stock market.",
        "projectTechnologies": ["Flutter", "Node.js", "Socket.io", "Express.js"],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/StockMarketGame",
    },
    {
        "projectName": "ElectricVehicles Website",
        "projectDescription": "A website to help people make informed decisions when buying electric vehicles.",
        "projectTechnologies": ["Python", "Flask", "HTML", "CSS", "JavaScript"],
        "link": "",
        "repo": "https://github.com/MananGandhi1810/FooBar-Electric-Vehicle-CyberCypher-Hackathon",
    },
]

languages = [
    "C",
    "C++",
    "Python",
    "Dart",
    "Kotlin",
    "Javascript",
    "Bash",
]

librariesAndFrameworks = [
    "Flutter",
    "Django",
    "Flask",
    "FastAPI",
    "Node.js",
    "Express.js",
    "React.js",
    "React Router",
    "React Native",
    "Next.js",
    "Arduino",
    "Pandas",
    "Numpy",
    "Scikit-Learn",
    "Jetpack Compose",
    "OpenCV",
    "Bootstrap",
    "TailwindCSS",
    "Prisma ORM",
    "Shadcn/UI",
]

tools = [
    "VSCode",
    "Android Studio",
    "Vim",
    "Neovim",
    "Windows",
    "Pop!_OS",
    "Ubuntu",
    "Raspberry Pi",
    "Play Console",
    "App Store Connect",
    "Postman",
    "Git",
    "GitHub",
    "Docker",
    "GitHub Actions",
    "Netlify",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Apache Kafka",
    "Google Colab",
    "Jupyter",
    "Cloudflare",
    "AWS",
    "Azure",
    "ClickHouse",
    "Firebase",
    "Supabase",
    "Appwrite",
    "Figma",
    "Adobe Photoshop",
]

banner_text = """███╗   ███╗ █████╗ ███╗   ██╗ █████╗ ███╗   ██╗ ██████╗  █████╗ ███╗   ██╗██████╗ ██╗  ██╗██╗
████╗ ████║██╔══██╗████╗  ██║██╔══██╗████╗  ██║██╔════╝ ██╔══██╗████╗  ██║██╔══██╗██║  ██║██║
██╔████╔██║███████║██╔██╗ ██║███████║██╔██╗ ██║██║  ███╗███████║██╔██╗ ██║██║  ██║███████║██║
██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║╚██╗██║██║   ██║██╔══██║██║╚██╗██║██║  ██║██╔══██║██║
██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║██║ ╚████║╚██████╔╝██║  ██║██║ ╚████║██████╔╝██║  ██║██║
╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝╚═╝"""

commands = {
    "WHOAMI": "Information about Manan Gandhi",
    "CHAT": "Start a conversation with the chatbot",
    "COMMAND": "List all available commands",
    "HELP": "Get detailed help about commands. Usage: HELP [command]",
    "HELLO": "Get server information and protocol details",
    "INFO": "Display server information",
    "PROJECTS": "List projects or get details about a specific project",
    "SKILLS": "Display skills categorized by languages, libraries, frameworks, and tools",
    "RESUME": "Get the link to Manan Gandhi's resume",
    "EXIT": "Exit the terminal session",
}
